version: 2.1

jobs:
  android-test:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - run: lsb_release -a
      - run: (yes || true) | sudo apt install sdkmanager
      - run: (yes || true) | sudo apt install android-sdk
      - run: sudo chmod -R 777 /usr/lib/android-sdk
      - run: |
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
      - run: (yes || true) | sdkmanager "tools" "platform-tools" "build-tools;33.0.1" "platforms;android-33" "emulator;31.3.9"
      - run: (yes || true) | sdkmanager --licenses
      - run: ./gradlew pixel2api31DebugAndroidTest

workflows:
  workflow:
    jobs:
      - android-test
