version: 2.1

jobs:
  my-job:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"

workflows:
  workflow:
    jobs:
      - android-test
