version: 2.1

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

jobs:
  android-test:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - run: lsb_release -a
      - checkout
      - run: python3 scripts/generateKsPropFile.py
      - restore_gradle_cache
      - run: ./gradlew tasks
      - save_gradle_cache
      - run: (yes || true) | sudo apt install sdkmanager
      - run: (yes || true) | sudo sdkmanager "tools" "platform-tools" "build-tools;33.0.1" "platforms;android-33" "emulator;31.3.9"
      - run: sudo chmod -R 777 /opt/android-sdk
      - run: (yes || true) | sdkmanager --licenses
      - run: |
          ls -la /opt/android-sdk
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
          echo $ANDROID_HOME
          echo $PATH
          ./gradlew assembleDebug

workflows:
  workflow:
    jobs:
      - android-test
