version: 2.1
orbs:
  android: circleci/android@2.1.2

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ arch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ arch }}-{{ checksum "build.gradle" }}

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ arch }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ arch }}-{{ checksum "build.gradle" }}

jobs:
  android-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.12.1
    steps:
      - run: lsb_release -a
      - checkout
      - run: python3 scripts/generateKsPropFile.py
      - run: sdkmanager --list
      - android/run-tests:
        system-image: system-images;android-29;default;x86

workflows:
  workflow:
    jobs:
      - android-test
