version: 2.1

commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}

jobs:
  android-test:
    machine:
      image: android:2022.12.1
    resource_class: large
    steps:
      - run: lsb_release -a
      - checkout
      - run: python3 scripts/generateKsPropFile.py
      - restore_gradle_cache
      - run: ./gradlew tasks
      - save_gradle_cache
      - run: sdkmanager --list
      - run: (yes || true) | sdkmanager "tools" "platform-tools" "build-tools;33.0.2" "platforms;android-33" "system-images;android-31;google_apis;x86_64"
      - run: (yes || true) | sdkmanager --licenses
      - run: ./gradlew pixel2api31DebugAndroidTest --stacktrace

workflows:
  workflow:
    jobs:
      - android-test
